version: '3'
services:
  local-mysql:
    image: mysql:8.0
    container_name: local-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    volumes:
      - ./mysql-conf:/etc/mysql/conf.d
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - local-network

  local-redis:
    image: redis:alpine
    container_name: local-redis
    command: ["redis-server", "--requirepass", "1234"]
    ports:
      - 6379:6379
    networks:
      - local-network

networks:
  local-network:
